# Generated by Django 5.1.4 on 2025-04-03 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, help_text='Очікувана тривалість завдання (наприклад, PT1H30M для 1 години 30 хвилин)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Фактично витрачений час'),
        ),
    ]
