# Generated by Django 5.1.4 on 2025-04-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order']},
        ),
    ]
