# Generated by Django 5.1.4 on 2025-04-23 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_column_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_due_dat_c36b93_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_assigne_41736d_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'assigned_to'], name='task_task_due_dat_fefac5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'order'], name='task_task_column__0d9560_idx'),
        ),
    ]
